### ISSUE TITLE
Error while test/modify nofification action: "extra keys not allowed @ data['entity_id']. Got None"

### ISSUE THREAD

**Issue by hanshanderson** [nielsfaber/alarmo#1051]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.6 / v1.10.5 / v1.10.4

### HA Version

2024.10.3

### Bug description

While testing an existing notification I'm getting following error message:

`extra keys not allowed @ data['entity_id']. Got None`

YAML code of existing notification:

```
service: notify.mobile_app_all
entity_id: null
data:
  message: >-
    Der Alarm konnte im Moment nicht scharfgeschaltet werden, aufgrund von:
    {{open_sensors|lang=de}}.
  title: Alarmo - Scharfschaltung fehlgeschlagen
```
Expecting that 'entity_id: null' is the reason for this. Deleting the line and saving  creates the following error message:

```
Something went wrong!
Message format incorrect: string value is None for dictionary value @ data['actions'][0]['entity_id']

Response error: 400

Please report the bug.
```

### Steps to reproduce

1. Create a new notification and before you save it try to send test notification -> test message will be send
2. Check YAML code -> No 'entity_id: null' visible
3. Save the notification
4. Reopen saved notification and try to test sending a test message -> Error message appears
5. Check YAML code -> 'entity_id: null' is added

Additional remarks:
- Initially expecting that the issue was related to new released v1.10.6. But with rollback to v1.10.5 and v1.10.4 same behaviour.
- If the notification is triggered by alarmo itself message is send without issues.

### Relevant log output

```shell
2024-10-23 22:50:35.423 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['entity_id']
```

**Comment by aheath70** [comment]
Exact same issue here

**Comment by micdesa** [comment]
Same here

**Comment by aheath70** [comment]
Temporary workaround if you need to modify your Alarmo notifications is to change the target to different one, and then change it back again to what it should be before clicking on "Save".

**Comment by mrichtarsky** [comment]
Unfortunately this seems to make it impossible to create any non-standard actions, e.g. for sending notifications on Android.

**Comment by Arnaud1977** [comment]
Exact same issue here

**Comment by nielsfaber** [comment]
I can confirm this issue. Its due to a change I made in the last release (v1.10.6).
However, this only affects the testing function. The notification should still work fine after saving.
I will make sure this is addressed in the next release. In the mean time I suggest to use the workaround of @aheath70.

**Comment by chah90** [comment]
@nielsfaber 
The issue does affect the yaml configuration as well. As soon as I hit the yaml button i cannot modify/Save the entry anymore. 
I initially intended to make the notifications critical on iOS.

**Comment by hesspoint** [comment]
same. Though irl when the actions are actually triggered I get some of the notifications on my iPhone but some I don't get. I think something is wrong in general

**Comment by Sim1Chin** [comment]
Same

**Comment by tackin** [comment]
Same for me. I'm on HA version 2024.11.2

**Comment by MnM001** [comment]
> I can confirm this issue. Its due to a change I made in the last release (v1.10.6). However, this only affects the testing function. The notification should still work fine after saving. I will make sure this is addressed in the next release. In the mean time I suggest to use the workaround of @aheath70.

@nielsfaber  Hi - the workaround only works till HA is re-started. After a restart it doesn't work anymore and have to go through the process again.
Any idea when the next version (which fixes the issues) will be released?

Thanks.

**Comment by iz8mbw** [comment]
Hello.
I suppose this issue can be cosed since it was fixed in version 1.10.7.
Is it true?

**Comment by nielsfaber** [comment]
@iz8mbw i hope so.
@hanshanderson can you confirm the new release solved the issue for you?

**Comment by tackin** [comment]
No sorry ... still get this after just trying to edit the name of the action:

Message format incorrect: string value is None for dictionary value @ data['actions'][0]['entity_id']
Response error: 400

**Comment by iz8mbw** [comment]
@tackin try to reboot HA and retry.

For me version 1.10.7 solved the issue.

**Comment by tackin** [comment]
HA asks to reboot after upgrading a HACS integration. So it was of coures rebootet also after updating Alarmo to 1.10.7

**Comment by nielsfaber** [comment]
@tackin the version number is displayed in the top right corner in the alarmo configuration pages. If this one is up to date, maybe there is still an issue that needs to be tackled. 
However I need a bit more insight in what you configured and try to do when it fails, since I (and some others) don’t experience any problems.
Screen capture videos are the best way to demonstrate a bug.

**Comment by tackin** [comment]
Yea ,,, works now!!!! 
I needed to delete all Browser-Cache and reload HA-Webpage. Stange, because I swichted on this computer afater having upgraded Alarmo via my mobile.

**Comment by hanshanderson** [comment]
> @iz8mbw i hope so. @hanshanderson can you confirm the new release solved the issue for you?

@nielsfaber : I have tested the new release (v1.10.7) and for me all is working fine now. Thank you for fixing the issue.

**Comment by nielsfaber** [comment]
Thanks all for the prompt responses, this issue can be closed 👍

**Comment by tackin** [comment]
Thank you Niels for your great work. I love this integration also for the prompt communication, maintanance of issues and reports.

**Comment by MnM001** [comment]
Thank you @nielsfaber !!!

**Comment by Arnaud1977** [comment]
Thank you !

**Comment by dick1980** [comment]
Error persists for me, v.1.10.7

**Comment by dick1980** [comment]
> Error persists for me, v.1.10.7

My apologies - it wasn't apparent to me that I had to remove the original automation and recreate it. Just editing the original automation made the error persist, creating a new one resolves the issue.
