### ISSUE TITLE
Error assigning disarming payload in MQTT Configuration

### ISSUE THREAD

**Issue by smotrs** [nielsfaber/alarmo#1322]
### Checklist

- [x] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [x] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

1.10.12

### HA Version

2025.11.3

### Bug description

Message format incorrect: extra keys not allowed @ data['mqtt'] ['state_payload']['disarming']

### Steps to reproduce

Try to enter, anything; disarming, disarm, 'disarming'. All results in same error above.

### Relevant log output

```shell

```

**Comment by nielsfaber** [comment]
Thanks for reporting this.
Alarmo doesn't implement a disarming state, so this setting doesn't make any sense.
I removed it from the code (https://github.com/nielsfaber/alarmo/commit/c40db6852cd8dd8ea156d97affd37abfd7839642).
I will inform you when the changes are released.

**Comment by nielsfaber** [comment]
This is fixed by updating alarmo to the v1.10.13 release.

**Comment by smotrs** [comment]
There a plan to remove the option completely or just disable it? It still shows on my screen under the MQTT Configuration soon for Alarmo which is why I'm wondering? I did the upgrade to .13 this morning. 👍

<img width="1440" height="3120" alt="Image" src="https://github.com/user-attachments/assets/36576529-8859-483a-859c-f60507e54b69" />
