### ISSUE TITLE
Alarmo 1.6.0 Error

### ISSUE THREAD

**Issue by hockey6611** [nielsfaber/alarmo#223]
I am on Home Assistant 2021.6.3 and just upgraded Alarmo 1.5.7 -> v1.6.0. I went to assign an area to a pre-existing notification and received this error:
![image](https://user-images.githubusercontent.com/28613898/121357262-a8414e80-c8ff-11eb-90dd-ba5c0020d4be.png)

The notification was working in the 1.5.7 release. In v1.6.0 it appears as though the notifications are not paired to any area. They are listed as "no area". I then reinstalled and reverted back to 1.5.7 and now all of my notifications and actions are missing from the UI. I will try to restore from backup.

**Comment by hockey6611** [comment]
I restored from a backup (and cleared browser cache) and everything has returned. I can try an upgrade again if there are any other steps or info you may need to diagnose.

**Comment by nielsfaber** [comment]
sorry for this problem, let's fix it quickly 😄

**Comment by nielsfaber** [comment]
There is a fix on the way: https://github.com/nielsfaber/alarmo/commit/abf61c8fa53914caf29c1ac4524537e65399d281

As temporary workaround you could switch to yaml view and remove the `entity_id` from the action.

**Comment by hockey6611** [comment]
Thanks for the quick work on this! I rely on this integration heavily, and greatly appreciate it!

**Comment by SmartM-ui** [comment]
> There is a fix on the way: [abf61c8](https://github.com/nielsfaber/alarmo/commit/abf61c8fa53914caf29c1ac4524537e65399d281)
> 
> As temporary workaround you could switch to yaml view and remove the `entity_id` from the action.

Hi,
I saw you closed my post as a duplicate. Sorry, I didn't notice this open issue.

I had tried, even before reading this message, to remove the code referring to entity_id, but still fails to save the settings reporting the same error.

I tried to uninstall and reinstall the custom component, but now I can't even create or modify a notification via yaml:

<img width="487" alt="Schermata 2021-06-10 alle 15 09 43" src="https://user-images.githubusercontent.com/63554131/121530651-e9b82380-c9fd-11eb-950e-432f08e21573.png">

<img width="508" alt="Schermata 2021-06-10 alle 15 07 41" src="https://user-images.githubusercontent.com/63554131/121530437-b7a6c180-c9fd-11eb-8210-869b5d66e893.png">

Thanks

**Comment by nielsfaber** [comment]
@hockey6611 Can you confirm the problem is solved in v1.6.1?
If so, please close the issue.

**Comment by hockey6611** [comment]
Thank you for the follow up. I wasn't able to upgrade until today. I seem to be still having issues. All of the Notifications have disappeared after the update, and all actions have moved to the "master" alarm.

I do have the master alarm disabled. Does that make a difference?

**Comment by nielsfaber** [comment]
The upgrade from v1.6.0 -> v1.6.1 contains no changes that can affect existing actions or notifications.
So the problems you are describing seem weird to me and I don't know how to help with you.
Can you check the `alarmo.storage` file in the `.storage` folder?
Please share the configuration of the actions as stored there.

**Comment by hockey6611** [comment]
Sorry I haven't been more helpful. I will gather those details for you. It may take a couple of days before I am able. Thank you!

**Comment by hockey6611** [comment]
This issue should remain closed. I have not been able to determine an absolute cause to my issue but I have reason to believe it was related to internal API requests. I had a similar http 400 error with the phpmyadmin addon.
