### ISSUE TITLE
Error while enabling mqtt

### ISSUE THREAD

**Issue by zbuh** [nielsfaber/alarmo#32]
Version used: 1.2.0
Going to settings, enable MQTT, save:

Response error: 500

I'm using MQTT in several other devices, without any issue.

Error reported in the log:

```
Logger: aiohttp.server
Source: custom_components/alarmo/alarm_control_panel.py:228 
First occurred: 8:15:58 AM (4 occurrences) 
Last logged: 8:17:55 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 172, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/config/custom_components/alarmo/websockets.py", line 98, in post
    await coordinator.async_update_config(data)
  File "/config/custom_components/alarmo/__init__.py", line 107, in async_update_config
    await self.config_callback()
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 228, in async_reload_config
    await self._unsubscribe_topics()
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by nielsfaber** [comment]
I accidently came across this bug myself as well.
It's a pretty harmless bug (after restarting HA all is OK and your settings are stored), but i will make sure to fix it.

**Comment by nielsfaber** [comment]
I just released v1.3.0 which should fix this issue.
Please try it out and close the issue if it is resolved.

**Comment by zbuh** [comment]
Just updated. but now the integration does not work.

```
Logger: homeassistant.setup
Source: setup.py:138 
First occurred: 5:07:19 PM (1 occurrences) 
Last logged: 5:07:19 PM

Setup failed for alarmo: Integration not found.
```

**Comment by nielsfaber** [comment]
Do you use HACS?
I accidently published this release with a folder 'alarmo' in the zip file, it caused the HACS installation to create an `/alarmo/alarmo` folder.
I'm quite new with this stuff, sorry about that.

**Comment by zbuh** [comment]
yes. I used Hacs

**Comment by nielsfaber** [comment]
Then please move the files one directory up, or try to reinstall with HACS (i corrected the release zip).

**Comment by zbuh** [comment]
Alarmo installation is now ok via Hacs.

But I still can't see the alarmo mqtt message in my broker.
Is there any config/setting for mqtt, behind state and command topic ?

**Comment by zbuh** [comment]
never mind. Got it now! Thanks. 
Closing the issue
