### ISSUE TITLE
Editor for actions turn on/off boolean/light/device broken

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo#369]
### Alarmo Version

v.1.8.2

### HA Version

2021.12.9

### Bug description

After upgrading to v1.8.2 actions which are turning booleans, lights or devices on or off cannot be edited anymore.
The UI just shows a blank page.
When creating such action, the yaml-mode doesn't work as soon as action turn on or turn off is selected in the UI.

### Steps to reproduce

- create an action which turns a boolean, light or device on or off
- try to edit that action

**Comment by nielsfaber** [comment]
should be fixed in v1.8.3

**Comment by ShadowRep** [comment]
Does not work for me. Still shows a blank page.

I have updated alarmo via HACS and restarted HA.
(Even manually redownloaded alarmo via HACS when it did not work the first time.)

Interestingly, it still shows v1.8.2 in the top right side on the alarmo pages
but HACS says the installed version is indeed v1.8.3.

**Comment by nielsfaber** [comment]
@ShadowRep So you're looking at the previous version, empty your browser cache.

**Comment by Eyco1981** [comment]
Try to refresh the browser cache by using Ctrl + F5 or clear the AH Companion App cache. Should work after that.

**Comment by ShadowRep** [comment]
Thanks for your fast help! It works now.
**Totally** my fault.

Never had this happen before (at least I don't now about it), so I was a bit confused.

Sorry for bothering you.
