### ISSUE TITLE
LoveLace Master Entry Delay Countdown with Multiple Zones not Correctly Reflecting the Shortest Delay When Triggered

### ISSUE THREAD

**Issue by stockmopar** [nielsfaber/alarmo#426]
### Alarmo Version

v1.8.5

### HA Version

2022.2.8

### Bug description

When Alarmo is configured with multiple zones.  For example, I have a Garage Zone and a House Zone.  I have Garage Zone configured to have an entry delay of 180 seconds and House Zone to have an entry delay of 30 seconds.  I would expect if Alarmo is armed that when the Garage Zone has a sensor that triggers the entry delay it would start counting from 180 seconds, then if a sensor in the House Zone is triggered the overall entry delay time would be the lower of the two. When I tested this, the Alarm itself is triggered at the appropriate time, but the master Countdown does not update to match.

### Steps to reproduce

1. Setup 2 zones ie Garage and House along with a Master zone.
2. Create a LoveLace Card for the Master zone.
3. Configure Garage Zone with a longer entry delay time ie 180 seconds.
4. Configure House Zone with a shorter entry delay time ie 30 seconds.
5. Configure a sensor (ie Garage Tilt Sensor) in the Garage Zone that is not in the House Zone.
6. Configure another sensor in the House Zone.
7. Trigger the Garage Tilt Sensor (starting the 180 second countdown)
8. Observe the countdown in the LoveLace Card (counting down from 180 seconds)
9. Now trigger a sensor in the House Zone 
10. The LoveLace card does not get updated to reflect the shorter countdown the House zone is driving **[Issue]**
11. The Alarm does appropriately trigger when shorter countdown expires.

### Relevant log output

```shell
N/A
```

**Comment by nielsfaber** [comment]
You are probably right.
Judging from the code I see that the master alarm has the pending/entry time set to the maximum of all areas:
https://github.com/nielsfaber/alarmo/blob/main/custom_components/alarmo/alarm_control_panel.py#L929-L934

If I understand correctly, your point is that this should become the minimum, right?

I agree this is better, as the master is programmed to proceed to triggered state as soon as the first area is triggered.

**Comment by nielsfaber** [comment]
This should be solved in https://github.com/nielsfaber/alarmo/commit/7438c2abc29930301e0c6a263e4c05b309586153
I will update you when the release is out.

**Comment by nielsfaber** [comment]
This should be fixed by updating to v1.9.0.
Please try it out, let me know if you still experience a problem after updating.

**Comment by stockmopar** [comment]
@nielsfaber Can we reopen this issue?

So I was able to retest this now with 1.9.3 being released which brings back the master countdown. But the following issue still happens. The countdown indication on the **Master** entity does not drop down to the lower of the 2 values. From the changes that you made I would have expected that this would have fixed this, but I wonder if there isn't _something else_ going on...

### Bug description

When Alarmo is configured with multiple zones. For example, I have a Garage Zone and a House Zone. I have Garage Zone configured to have an entry delay of 180 seconds and House Zone to have an entry delay of 30 seconds. I would expect if Alarmo is armed that when the Garage Zone has a sensor that triggers the entry delay it would start counting from 180 seconds, then if a sensor in the House Zone is triggered the overall entry delay time would be the lower of the two. When I tested this, the Alarm itself is triggered at the appropriate time, but the master Countdown does not update to match.

### Steps to reproduce

1. Setup 2 zones ie Garage and House along with a Master zone.
2. Create a LoveLace Card for the Master zone.
3. Configure Garage Zone with a longer entry delay time ie 180 seconds.
4. Configure House Zone with a shorter entry delay time ie 30 seconds.
5. Configure a sensor (ie Garage Tilt Sensor) in the Garage Zone that is not in the House Zone.
6. Configure another sensor in the House Zone.
7. Trigger the Garage Tilt Sensor (starting the 180 second countdown)
8. Observe the countdown in the LoveLace Card (counting down from 180 seconds)
9. Now trigger a sensor in the House Zone
10. The LoveLace card does not get updated to reflect the shorter countdown the House zone is driving [Issue]
11. The Alarm does appropriately trigger when shorter countdown expires.

**Comment by stockmopar** [comment]
Here are a couple pictures hopefully they will help explain. The item "Home Alarm" card is the master entity. The "House" card is the "House Zone" and the "Garage" card is the "Garage Zone as described in the previous steps.

![IMG_2600](https://user-images.githubusercontent.com/6521389/167469094-d28194b2-94bd-47b8-a6ec-90e1e1c7c085.jpg)

![IMG_2601](https://user-images.githubusercontent.com/6521389/167469109-a4c3a27d-d9c5-4fbe-bf63-b63c88f9b543.jpg)

**Comment by stockmopar** [comment]
So I think this might be tied to the fact that in:

https://github.com/nielsfaber/alarmo/blob/f2838605ffabb3c4bd8dac0e0a109c97e63ad3aa/custom_components/alarmo/alarm_control_panel.py#L924

The Master state was STATE_ALARM_PENDING (self._state would be equal to STATE_ALARM_PENDING]:) and the "new state" being requested is STATE_ALARM_PENDING (state == STATE_ALARM_PENDING) so that block of code would not get executed.  I think this is causing self.delay from getting updated and would prevent some type of event from being generated at that time for the master alarm.

We would need to know how much time is left for the area alarms (use item.expiration?) that are pending and only set an event (maybe a new event called "alarmo_delay_reduced"?)  

For the Ring Keypad v2 blueprint to end up being able to work with this we need at minimum a new event at that time and a way to know (likely through the updated delay value) how many seconds the countdown should be set to.

@nielsfaber 
@ImSorryButWho

**Comment by stockmopar** [comment]
I have added this code into:

https://github.com/nielsfaber/alarmo/blob/f2838605ffabb3c4bd8dac0e0a109c97e63ad3aa/custom_components/alarmo/alarm_control_panel.py#L912

class AlarmoMasterEntity(AlarmoBaseEntity): async def async_update_state(self, state: str = None):

Right after:

```
arm_modes = [
            item.arm_mode
            for item in self.hass.data[const.DOMAIN]["areas"].values()
        ]
        arm_mode = arm_modes[0] if len(set(arm_modes)) == 1 else None
```

And it seems to correctly detects when the delay needs to be shortened (and when it doesn't need to be shortened).

```
if state == STATE_ALARM_PENDING and self._state == STATE_ALARM_PENDING:
            needs_delay_update = False
            if self.expiration:
                diff = self.expiration - dt_util.utcnow()
                if self.delay:
                    old_delay = self.delay
                    new_delay = diff.total_seconds()
                    
                    for item in self.hass.data[const.DOMAIN]["areas"].values():
                        if item.delay:
                            if item.delay < new_delay:
                                new_delay = item.delay
                                needs_delay_update = True
                                _LOGGER.debug("Master: Needs update")
                    if needs_delay_update == True:
                        self.delay = new_delay
                        _LOGGER.debug("entity {} delay was updated from {} to {}".format(self.entity_id, old_delay, new_delay))
                        async_dispatcher_send(self.hass, "alarmo_delay_updated", None, old_delay, new_delay)
```

This doesn't currently update the actual countdown value in the Master alarmo-card (not quite sure yet on the workflow to edit cards yet) and don't believe it will trigger the updated delay command to be sent to Ring Keypad v2 yet... but progress!

**Comment by stockmopar** [comment]
I was able to get this working for updating the countdown with the Ring Keypad v2 (not on the Alarmo-Card) with the following code:

```
        if state == STATE_ALARM_PENDING and self._state == STATE_ALARM_PENDING:
            needs_delay_update = False
            if self.expiration:
                diff = self.expiration - dt_util.utcnow()
                if self.delay:
                    old_delay = self.delay
                    new_delay = diff.total_seconds()
                    
                    for item in self.hass.data[const.DOMAIN]["areas"].values():
                        if item.delay:
                            if item.delay < new_delay:
                                new_delay = item.delay
                                needs_delay_update = True
                                _LOGGER.debug("Master: Needs update")
                    if needs_delay_update == True:
                        self.delay = new_delay
                        _LOGGER.debug("entity {} delay was updated from {} to {}".format(self.entity_id, old_delay, new_delay))
                        async_dispatcher_send(self.hass, "alarmo_state_updated", None, state, state)
                        self.async_write_ha_state()
                        data = dict(**{
                            "area_id": self.area_id,
                            "delay": new_delay,
                        })
                        self.hass.bus.fire("alarmo_delay_updated", data)
```

And by adding another trigger to the RingKeypadV2 blueprint:

```
- platform: event
  event_type: alarmo_delay_updated
  id: update_delay
```

And condition:

```
  - conditions:
    - condition: trigger
      id: update_delay
    sequence:
    - service: zwave_js.set_value
      target:
        device_id: !input 'keypad'
      data:
        command_class: '135'
        endpoint: '0'
        property: '17'
        property_key: '7'
        value: '{{ state_attr(alarm, ''delay'') }}'
```

@nielsfaber 
@ImSorryButWho

**Comment by nielsfaber** [comment]
@stockmopar I think I misread your original bug report.
It wasn't quite clear to me that you were referring to updating of the master entity due to the area entities changing sequentially.
Thanks a lot for pointing this out and for digging into this 👍 

I think the code needs to be revised and also consider exit delay case (arming state), where the same situation may occur.
Your code example is a good starting point but I wish to 'centralize' the calculation of time delay into a single function.

I don't think there is a need for introducing a new HA event for this case.
It should be sufficient to subscribe to state changes in the delay attribute of the alarm_control_panel entity.
What do you think?

**Comment by stockmopar** [comment]
@nielsfaber 

I figured you would have a much better way to integrate this. So yes that all sounds great. I was thinking the same thing on the state changes, but for some reason when I had tried that I didn't get the state changes to come through (most likely attributed to something else I was doing wrong). I wasn't sure if you update an attribute if it actually changes "state" as the actual "state" in this scenario would be from "pending" to "pending" but the delay attribute would be different.

With arming/exiting... that's an interesting case... as the master.

Based on this logic:

![image](https://user-images.githubusercontent.com/6521389/168176168-ef03bfd1-b943-4135-9cfb-35f26f8ce03a.png)

I would say the countdown to exit/arm should be countdown until the master is expected to be armed which would technically be the maximum of the countdowns that are left.

Now just as a tangent, my wife and I were talking about this and at one point we talking about how it kind of depended on which zone the "master keypad" actually resided in. Which... is impossible to know when its on a dashboard and the user is mobile and quickly led us to come to we should maybe just set all the exit delays to be the same. Although I still think there will be some who would want different exit delays. Even in my case I would likely set a 60 second delay if it was just house but would need a 180 second exit delay for the garage in any case.

A couple other off the wall ideas... would be for a master alarm/card... when arming: 
- show all the countdowns (and which zones are already armed)
- give an option for which specific zone the master countdown should correspond to

**Comment by ImSorryButWho** [comment]
In terms of the Ring keypad blueprint, we can trigger on the `delay` attribute changing.  I'd probably replace the pending / arming state trigger with one that looks for delay to change to a non-null value, then checks the state (pending / arming), and fires the appropriate indicator with the new delay value.  I haven't tested that, but I don't think it should be a problem.

**Comment by nielsfaber** [comment]
@stockmopar I made commit https://github.com/nielsfaber/alarmo/commit/8d06470c168df70be03a25e862d13685a476abef to address the issue.
Changes were made to update the `delay` and `open_sensors` property of the master alarm based on the sensor event which causes the alarm to reach the `triggered` state first.
If you would to help please test the modifications locally (you seem comfortable with editing python.
I will not yet release this as I have some other things to tackle first.

@ImSorryButWho To keep the Ring keypad in sync (I don't know if it has an internal countdown) you would need to watch for changes in `delay` attribute. I made a local test ([this ](https://www.home-assistant.io/docs/automation/trigger/#triggering-on-attribute-changes)method) and it works fine. If you would prefer to have Alarmo trigger an event, please let me know.
