### ISSUE TITLE
Alarmo side panel 'stuck' on "Loading..."

### ISSUE THREAD

**Issue by MrMxyzptlk** [nielsfaber/alarmo#688]
### Alarmo Version

v1.9.7

### HA Version

2023.4.0b2

### Bug description

Alarmo installed and working, device and entity showing properly, side panel when clicked just shows "Loading..." in upper left corner of main HA screen indefinitely.

Uninstalling and reinstalling with a reboot with same results.

No errors in logs.

### Steps to reproduce

Alarmo installed and working, device and entity showing properly, side panel when clicked just shows "Loading..." in upper left corner of main HA screen indefinitely.

### Relevant log output

```shell
No messages in logs for Alarmo.
```

**Comment by jclendineng** [comment]
yea something broke it coming from b1 to b2, I checked the changelog though and can't find a breaking change that would cause it.

**Comment by nielsfaber** [comment]
I can confirm this problem.
It seems to be caused by some changes made in HA for the upcoming 2023.5 release.

**Comment by computermaster0101** [comment]
On new install its an issue as well.

**Comment by nielsfaber** [comment]
This is fixed in https://github.com/nielsfaber/alarmo/commit/09199653e067eeb6d5b3128949a44740a6164835.
I will make sure to publish a release soon, since the next HA release is probably next Wednesday.

**Comment by jclendineng** [comment]
FYI you can roll back:

ha core update version=2023.3.6

Thank you for this integration by the way, amazing alarm system, super happy with it.

**Comment by nielsfaber** [comment]
I released v1.9.8 which contains the fix.
Hope this solves the problem for everyone.

**Comment by mploetner** [comment]
Running 2023.4.0b7 and the latest Alarmo update I still have the bug. Any suggestions?

**Comment by nielsfaber** [comment]
@mploetner are you on v1.9.8?
Is this version also displayed in the top right corner when opening the alarmo panel?

**Comment by mploetner** [comment]
What panel do you refer to? I can't open the settings. That's the problem. I updated to the 1.98 this morning via HACS

**Comment by mploetner** [comment]
Ok now I know what you asked for ![image](https://user-images.githubusercontent.com/29687607/230032247-060dde85-494f-4402-aa04-03382c12c4b6.jpeg)

**Comment by jclendineng** [comment]
It works for me!

**Comment by mploetner** [comment]
Tried it on multiple devices. Same error

**Comment by smarthomefamilyverrips** [comment]
@nielsfaber after update to HA 2023.4 I have same when trying to open settings on mobile app, then I also gete the loading in left corner, if I open HA in web browser using nabucasa external link then it opens setting panel. I am on 1.9.8

![Screenshot_20230406_000541_Home Assistant](https://user-images.githubusercontent.com/97987488/230211993-40a7d169-4ecb-4329-ac24-aef2259b046e.jpg)

**Comment by freneatcharley** [comment]
same problem here v1.9.8 but alarmo stuck at loading. HA up to date on v2023.04.0 (supervisor and HA)

**Comment by smarthomefamilyverrips** [comment]
At me started working when I did switch from mobile to local internet while already have the settings page open forcing HA mobile app to reconnect automatically to local link.... also did do same while connected on web browser and now also on web browser it works on local and nabucase link.... maybe is/was a cache problem for me

**Comment by freneatcharley** [comment]
cache problem I think yes it works with my android app ! thx !

**Comment by zjakzbigniew** [comment]
I had the same issue. Clearing cache in my browser seemed to help.

**Comment by mploetner** [comment]
Ok clearing cache worked for me in browser. But for mobile app I had to reinstall the app to get it work (or I missed a way to clear cache there)

Thx all for the help

**Comment by smarthomefamilyverrips** [comment]
@mploetner for me normal total closing app and restart phone does work

**Comment by mploetner** [comment]
> @mploetner for me normal total closing app and restart phone does work

Didn't work here but meanwhile I found the clear cache option in the app. So I'm prepared for next time. Thx :)

**Comment by smarthomefamilyverrips** [comment]
@mploetner is there a clear cache option within app? Or you refer to the option to clear cache data from apps within phone settings?

**Comment by mploetner** [comment]
@smarthomefamilyverrips its in the app settings under "Debugging"

**Comment by YewTreeWeb** [comment]
I’ve just updated to Alarmo v1.9.8 and still getting the same issue of the side panel screen just saying ‘loading…’

**Comment by smarthomefamilyverrips** [comment]
> I’ve just updated to Alarmo v1.9.8 and still getting the same issue of the side panel screen just saying ‘loading…’

@YewTreeWeb did you try clearing cache in app and/or browser? This did solve it for most of us.

**Comment by YewTreeWeb** [comment]
> > I’ve just updated to Alarmo v1.9.8 and still getting the same issue of the side panel screen just saying ‘loading…’
> 
> @YewTreeWeb did you try clearing cache in app and/or browser? This did solve it for most of us.

Thanks for the reply. I had to clear frontend cache and restart the app to get it working 🙂

**Comment by smarthomefamilyverrips** [comment]
> > > I’ve just updated to Alarmo v1.9.8 and still getting the same issue of the side panel screen just saying ‘loading…’
> > 
> > 
> > @YewTreeWeb did you try clearing cache in app and/or browser? This did solve it for most of us.
> 
> Thanks for the reply. I had to clear frontend cache and restart the app to get it working 🙂

@YewTreeWeb with pleasure! 👍🏻

**Comment by Shaunpottie** [comment]
It's 8th of April 2023, I have the same problem when clicking on the Alarmo side panel, it just says loading and nothing happens?

**Comment by kallejoken** [comment]
i have also updated to the latest and also have the problem - locally on the browser. on the phone it works. cache in the browser i have already deleted

**Comment by Lazzapao** [comment]
I had the same problem. Working on the mobile and not working at home
Deleting the cache on the browser (chrome) now its working on both.
I am updated on Alarmo 1.9.8 and HA 2023.4.2

**Comment by aaroncorry** [comment]
Recently Updated Home Assistant, and the Alarmo Update. Still having this issue too.

**Comment by almico** [comment]
Home Assistant 2023.4.2
Alarmo Firmware: 1.9.8

Before updating to 1.9.8, I got the "Loading...".
Now everything is working properly.
Thank you.

**Comment by joelquadros** [comment]
Hi guys!

Facing same issue here.

Home Assistant 2023.4.2
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230406.1 - latest

Alarmo
by @nielsfaber
Firmware: 1.9.8

**Comment by amadorpozo** [comment]
fixed after upgrading to 1.9.8 and cleaning cache in Firefox (settings => search for "cache" => click on Clear Data => tick only cached web content => clear) and for the Android app (settings => Applications => HomeAssistant => Storage and Cache => Clean Cache)

**Comment by joelquadros** [comment]
when I clean cache It works on firefox and edge but not in chrome

**Comment by Sch0field9** [comment]
For Chrome users, who dont want to delete their cache and ctrl + F5 not working:
Open Dev Tools (ctrl+shift+I) and refresh again.
if that does not work: ctrl+shift+I > F1 > under "Network" make sure the "disable cache (while DevTools is open)" is checked
