### ISSUE TITLE
Field "area" cannot be left empty when creating actions or notifications

### ISSUE THREAD

**Issue by skaggerik** [nielsfaber/alarmo#909]
### Alarmo Version

v1.9.15

### HA Version

2024.3.1

### Bug description

Field for area should be left empty for the action to trigger regardless of area. This field may not be left empty. See screenshot.
![image](https://github.com/nielsfaber/alarmo/assets/155855409/59ce8f57-793e-4254-bffc-0d49f831740b)

### Steps to reproduce

1. Create several areas
2. Click new notification/action
3. Clear out field for area
4. Add a sample action 
5. Note error message when trying to save

**Comment by skaggerik** [comment]
Edit: fixed reproduction steps.

**Comment by nielsfaber** [comment]
I think the text above the item is outdated. 
'leave empty to select global alarm' is no longer applicable. When creating the action / notification, the master alarm should be selectable from the list as well as any area. The master should also be filled in as default.
Choosing neither option is not allowed.
I will make sure the text is adapted for this.

**Comment by nielsfaber** [comment]
This should be fixed in the v1.10.0 release of alarmo, the text should no longer introduce misunderstanding.
Please update and let me know if the issue is solved for you now.

**Comment by skaggerik** [comment]
> This should be fixed in the v1.10.0 release of alarmo, the text should no longer introduce misunderstanding. Please update and let me know if the issue is solved for you now.

Dearest sir, 

This issue is now solved, many thanks!

P.s. the top right text still says "v1.9.15".

**Comment by skaggerik** [comment]
See comment above. I messed up closing the issue.

**Comment by nielsfaber** [comment]
> P.s. the top right text still says "v1.9.15".

I think this is due to your browser cache. 
You will probably also still see the old text next to the field for entering the area too.
Force-refreshing the page should help.
Thanks a lot for donating to the project, I will look into the remaining issue as well 👍
